services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - STORAGE_PATH=/app/storage
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_ENV=development
      - PYTHONPATH=/app
    depends_on:
      - qdrant
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - STORAGE_PATH=/app/storage
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_BASE_URL=http://api:8000
      - APP_ENV=development
      - PYTHONPATH=/app
    depends_on:
      - qdrant
      - api
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  qdrant_data:
