# Base configuration for RAG system
app:
  name: "RAG System"
  version: "0.1.0"
  description: "Retrieval Augmented Generation system with Qdrant and LangChain"

qdrant:
  host: "localhost"
  port: 6333

langchain:
  embedding_model: "text-embedding-ada-002"
  multilingual_embedding_model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  llm_model: "gpt-3.5-turbo"
  temperature: 0.0

storage:
  document_path: "./storage/documents"
  
indexing:
  chunk_size: 1000
  chunk_overlap: 200
  batch_size: 10

languages:
  supported:
    - "en"
    - "ru"
  default: "en"
  auto_detect: true
  detect_chunk_language: false

translation:
  enabled: true
  preload_models: false
  enabled_pairs:
    - ["ru", "en"]
    - ["en", "ru"]

# Agent configuration
agent:
  # Default agent settings
  default_agent_name: "RAG Assistant"
  default_agent_description: "Agent for RAG with self-assessment"
  
  # Action configuration
  actions:
    enabled:
      - "search"
      - "generate"
      - "evaluate"
      - "improve"
  
  # Planning configuration
  planning:
    enabled: true
    max_steps: 10
    timeout: 120  # seconds

# Self-assessment configuration
evaluation:
  # Criteria thresholds (0.0 to 1.0)
  thresholds:
    relevance: 0.7
    factual_accuracy: 0.8
    completeness: 0.7
    logical_coherence: 0.7
    ethical_compliance: 0.9
  
  # Criteria weights for overall score
  weights:
    relevance: 0.25
    factual_accuracy: 0.3
    completeness: 0.2
    logical_coherence: 0.15
    ethical_compliance: 0.1
  
  # Overall threshold for improvement
  overall_threshold: 0.75
  
  # Maximum improvement attempts
  max_improvement_iterations: 2

# Comprehensive logging configuration
logging:
  # Basic logging settings
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Structured logging settings
  structured:
    enabled: true
    include_correlation_id: true
    format_type: "structured"  # "structured" or "standard"
  
  # File logging
  file:
    enabled: false
    path: "./logs/rag-system.log"
    max_size_mb: 100
    backup_count: 5
    rotation: "time"  # "time" or "size"
  
  # Component-specific logging levels
  components:
    document_processing: "INFO"
    vector_operations: "INFO"
    search_queries: "INFO"
    agent_operations: "INFO"
    translation: "INFO"
    embedding_generation: "INFO"
    text_splitting: "INFO"
    progress_tracking: "INFO"
    performance_metrics: "INFO"
    business_events: "INFO"
    user_actions: "INFO"
    system_metrics: "INFO"
    error_tracking: "ERROR"
  
  # Progress tracking settings
  progress:
    enabled: true
    batch_log_interval: 10  # Log every N items
    percentage_log_interval: 10.0  # Log every N percent
    time_log_interval: 30  # Log every N seconds
  
  # Performance monitoring
  performance:
    enabled: true
    slow_operation_threshold: 5.0  # seconds
    log_all_operations: false
    log_slow_operations: true
  
  # Correlation tracking
  correlation:
    enabled: true
    header_name: "X-Correlation-ID"
    auto_generate: true
  
  # Error tracking
  error_tracking:
    enabled: true
    include_stack_trace: true
    max_error_message_length: 1000
    log_error_context: true
  
  # Metrics and monitoring
  metrics:
    enabled: true
    system_metrics_interval: 60  # seconds
    business_metrics_enabled: true
    performance_metrics_enabled: true
