# Base configuration for RAG system
app:
  name: "RAG System"
  version: "0.1.0"
  description: "Retrieval Augmented Generation system with Qdrant and LangChain"

qdrant:
  host: "localhost"
  port: 6333

langchain:
  embedding_model: "text-embedding-ada-002"
  multilingual_embedding_model: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  llm_model: "gpt-3.5-turbo"
  temperature: 0.0

storage:
  document_path: "./storage/documents"
  
indexing:
  chunk_size: 1000
  chunk_overlap: 200
  batch_size: 10

languages:
  supported:
    - "en"
    - "ru"
  default: "en"
  auto_detect: true
  detect_chunk_language: false

translation:
  enabled: true
  preload_models: false
  enabled_pairs:
    - ["ru", "en"]
    - ["en", "ru"]

# Agent configuration
agent:
  # Default agent settings
  default_agent_name: "RAG Assistant"
  default_agent_description: "Agent for RAG with self-assessment"
  
  # Action configuration
  actions:
    enabled:
      - "search"
      - "generate"
      - "evaluate"
      - "improve"
  
  # Planning configuration
  planning:
    enabled: true
    max_steps: 10
    timeout: 120  # seconds

# Self-assessment configuration
evaluation:
  # Criteria thresholds (0.0 to 1.0)
  thresholds:
    relevance: 0.7
    factual_accuracy: 0.8
    completeness: 0.7
    logical_coherence: 0.7
    ethical_compliance: 0.9
  
  # Criteria weights for overall score
  weights:
    relevance: 0.25
    factual_accuracy: 0.3
    completeness: 0.2
    logical_coherence: 0.15
    ethical_compliance: 0.1
  
  # Overall threshold for improvement
  overall_threshold: 0.75
  
  # Maximum improvement attempts
  max_improvement_iterations: 2
