# Production environment configuration
app:
  debug: false

api:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 4

logging:
  level: "INFO"
  file: "/var/log/rag-system/app.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Preload translation models for faster response
translation:
  preload_models: true
